server:
  port: 8081
spring:
  mail:
    host: smtp.qq.com
    username: xxx.@qq.com
    password: your authorization code
    to-email: xxx.@qq.com,yyy.@qq.com
threshold:
  cpu-temperature: 90
  disk-available-percent: 0.2
logging:
  file:
    path: /app/log
